[ids]
*

[main]
q = overloadt(nav, apostrophe, 200)
w = ,
e = .
r = p
t = y
y = f
u = g
i = c
o = r
p = l

a = overloadt(shift, a, 200)
s = overloadt(control, o,200)
d = overloadt(meta, e, 200)
f = overloadt(numlay, u, 200)
g = i
h = d
j = overloadt(numlay, h, 200)
k = overloadt(meta, t, 200)
l = overloadt(control, n, 200)
semicolon = overloadt(shift, s, 200)

x = q
c = j
v = k
b = x
n = b
comma = w
. = v
/ = z

backspace = capslock
capslock = backspace
leftmeta+leftshift+f23 = leftcontrol
equal = toggle(mousemode)

[numlay]
q = /
w = 1
e = 2
r = 3
t = +
y = @
u = {
i = }
o = (
p = )

a = equal
s = 4
d = 5
f = 6
g = minus
h = #
j = leftbrace
k = rightbrace
l = <
semicolon = >

z = 7
x = 8
c = 9
v = 0
b = *
n = "

[shift]
capslock = delete

[nav]
j = left
c = down
v = up
p = right
q = mute
e = volumeup
w = volumedown
u = brightnessdown
i = brightnessup
t = home
g = end
a = pageup
s = pagedown
f = leftmouse
d = rightmouse
l = scrollup
k = scrolldown

[mousemode]
f = leftmouse
d = rightmouse
v = scrollup
c = scrolldown
