[ids]
*

[main]
tab = overload(nav, tab)
backspace = capslock
capslock = backspace
leftmeta+leftshift+f23 = leftcontrol

equal = toggle(mousemode)

[shift]
capslock = delete
# ---------------------------------------------------------
# LAYER 5: NAV (Hold Caps Lock)
# ---------------------------------------------------------
[nav]
j = left
c = down
v = up
p = right
q = mute
e = volumeup
w = volumedown
u = brightnessdown
i = brightnessup
t = home
g = end
a = pageup
s = pagedown
f = leftmouse
d = rightmouse
l = scrollup
k = scrolldown

[mousemode]
f = leftmouse
d = rightmouse
v = scrollup
c = scrolldown
