[ids]
*

[main]
capslock = overload(nav, backspace)
backspace = capslock

leftmeta+leftshift+f23 = leftcontrol

grave = toggle(minecraft)
# ---------------------------------------------------------
# LAYER 5: NAV (Hold Caps Lock)
# ---------------------------------------------------------
[nav]
j = left
c = down
v = up
p = right
q = mute
e = volumeup
w = volumedown
u = brightnessdown
i = brightnessup
t = home
g = end
a = pageup
s = pagedown
f = leftmouse
d = rightmouse
l = scrollup
k = scrolldown

[minecraft]
f = leftmouse
d = rightmouse
v = scrollup
c = scrolldown
